# Generated by Django 5.0.2 on 2024-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='cam1.jpeg', max_length=100),
        ),
    ]
