# Generated by Django 5.0.2 on 2024-03-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs_api', '0004_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
