# Generated by Django 5.0.2 on 2024-03-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_api', '0007_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Furnitures', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
